### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a container to hold the car element in.
- [x] Add the car element to the page.
- [x] Add the appropriate positioning to the car element.
- [x] Remove any unnecessary CSS styling.
- [x] Fix all bugs/errors.
