### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  Create CSS classes to rotate the car image using the transform property, the CSS function rotate, and the transition property.
- [x] Add an event listener to the document for the keydown event.
- [x] Create functions that apply the appropriate CSS styling in response to which arrow key was pressed. 
- [x] Remove any unnecessary CSS styling.
- [x] Fix all bugs/errors.
