### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Create a data model to store the car element's x and y coordinates on the page.
- [x] Create a function in response to the keydown event for the space key.
- [x] Use the style property to update the car element's top and left properties.
- [x] Update the car's coordinates within the data model. 
- [x] Create an interval function so that the previous function occurs every 16 milliseconds.
- [x] Remove any unnecessary CSS styling.
- [x] Fix all bugs/errors.
