### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a property to the data model to indicate whether the car is on or off with a boolean value. Set the default to false/off.
- [x] The first time the space key is pressed, the value should switch to true/on.
- [x] When the space key is pressed again, the value should switch to false/off and the interval that makes the car move forward should be cleared. 
- [x] Each time the space key is pressed, the value should change.
- [x] Remove any unnecessary CSS styling.
- [x] Fix all bugs/errors.
