### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Create a function that checks the direction of the car and updates the car's coordinates accordingly. 
- [x] Call the previously created function within the setInterval function. 
- [x] Remove any unnecessary CSS styling.
- [x] Fix all bugs/errors.
